In [5]:
import numpy as np

#Create array using array
##Create a 1D array

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
#Reshape an array

arr2 = np.array(['Om', 'Bhushan', 'Tambat'])
print(arr2)

arr3 = arr2.reshape(1, 3)
print(arr3)

#2d Array
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr4)

arr4.reshape(2, 3)

['Om' 'Bhushan' 'Tambat']
[['Om' 'Bhushan' 'Tambat']]
[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.arange(0, 11, 2).reshape(3, 2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [49]:

np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
#Universal functions
#
arr5 = np.array([1, 2, 3, 4, 5])

#spare root
print(np.sqrt(arr5))

#Exponential
print(np.exp(arr5))

#Sine
print(np.sin(arr5))

#natual log
print(np.log(arr5))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [72]:
#Array slicing and indexing

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

print("___________________________")

X = arr[0][1]
print(X)

Y = arr[1, 2]
print(Y)

z = arr[0:2, 2:]
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
___________________________
2
7
[[3 4]
 [7 8]]


In [75]:
#statistical concepts (normalization)

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

#Calculate mean
mean = np.mean(data)
print("Mean:", mean)

sd = np.std(data)
print("Standard Deviation:", sd)

#normalization
normalized_data = (data - mean) / sd
print("Normalized Data:", normalized_data)

Mean: 5.5
Standard Deviation: 2.8722813232690143
Normalized Data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [ ]:
#Logical operations
arr6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr6>5

arr6[(arr6>=4) & (arr6<=9)]



array([4, 5])